- hosts: all
  connection: local
  become: true

  vars_files:
    - vault

  tasks:

    - set_fact:
        ansible_python_interpreter: /usr/bin/python3
  
    - name: Sprawdzanie systemu
      fail: msg="System operacyjny to nie UBUNTU 22"
      when: ansible_distribution != "Ubuntu" and ansible_distribution_major_version | int != 22


    - import_tasks: repo.yml    

    - import_tasks: pakiety.yml
      tags: pakiety
 
    - import_tasks: konfiguracja.yml
    
#    - import_tasks: sterowniki.yml

    - name: Informacja
      debug:
        msg: "Instalacja zostala zakonczona. Komputer zostanie automatycznie zrestartowany. Prosze czekac..."

    - pause:
        seconds: 5

    - name: Restart komputera
      command: reboot
